/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CodeOfEthicsRouteImport } from './routes/code-of-ethics'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HomeopathyRouteImport } from './routes/homeopathy'
import { Route as MentoringRouteImport } from './routes/mentoring'
import { Route as NewPatientQuestionnaireRouteImport } from './routes/new-patient-questionnaire'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiPublicAirtableTestCleanupRouteImport } from './routes/api/public/airtable-test-cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfEthicsRoute = CodeOfEthicsRouteImport.update({
  id: '/code-of-ethics',
  path: '/code-of-ethics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeopathyRoute = HomeopathyRouteImport.update({
  id: '/homeopathy',
  path: '/homeopathy',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoringRoute = MentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPatientQuestionnaireRoute = NewPatientQuestionnaireRouteImport.update({
  id: '/new-patient-questionnaire',
  path: '/new-patient-questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAirtableTestCleanupRoute =
  ApiPublicAirtableTestCleanupRouteImport.update({
    id: '/api/public/airtable-test-cleanup',
    path: '/api/public/airtable-test-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-ethics': typeof CodeOfEthicsRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/homeopathy': typeof HomeopathyRoute
  '/mentoring': typeof MentoringRoute
  '/new-patient-questionnaire': typeof NewPatientQuestionnaireRoute
  '/privacy': typeof PrivacyRoute
  '/supervision': typeof SupervisionRoute
  '/terms': typeof TermsRoute
  '/api/public/airtable-test-cleanup': typeof ApiPublicAirtableTestCleanupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-ethics': typeof CodeOfEthicsRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/homeopathy': typeof HomeopathyRoute
  '/mentoring': typeof MentoringRoute
  '/new-patient-questionnaire': typeof NewPatientQuestionnaireRoute
  '/privacy': typeof PrivacyRoute
  '/supervision': typeof SupervisionRoute
  '/terms': typeof TermsRoute
  '/api/public/airtable-test-cleanup': typeof ApiPublicAirtableTestCleanupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/code-of-ethics': typeof CodeOfEthicsRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/homeopathy': typeof HomeopathyRoute
  '/mentoring': typeof MentoringRoute
  '/new-patient-questionnaire': typeof NewPatientQuestionnaireRoute
  '/privacy': typeof PrivacyRoute
  '/supervision': typeof SupervisionRoute
  '/terms': typeof TermsRoute
  '/api/public/airtable-test-cleanup': typeof ApiPublicAirtableTestCleanupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/code-of-ethics'
    | '/consultations'
    | '/contact'
    | '/homeopathy'
    | '/mentoring'
    | '/new-patient-questionnaire'
    | '/privacy'
    | '/supervision'
    | '/terms'
    | '/api/public/airtable-test-cleanup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/code-of-ethics'
    | '/consultations'
    | '/contact'
    | '/homeopathy'
    | '/mentoring'
    | '/new-patient-questionnaire'
    | '/privacy'
    | '/supervision'
    | '/terms'
    | '/api/public/airtable-test-cleanup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/code-of-ethics'
    | '/consultations'
    | '/contact'
    | '/homeopathy'
    | '/mentoring'
    | '/new-patient-questionnaire'
    | '/privacy'
    | '/supervision'
    | '/terms'
    | '/api/public/airtable-test-cleanup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CodeOfEthicsRoute: typeof CodeOfEthicsRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContactRoute: typeof ContactRoute
  HomeopathyRoute: typeof HomeopathyRoute
  MentoringRoute: typeof MentoringRoute
  NewPatientQuestionnaireRoute: typeof NewPatientQuestionnaireRoute
  PrivacyRoute: typeof PrivacyRoute
  SupervisionRoute: typeof SupervisionRoute
  TermsRoute: typeof TermsRoute
  ApiPublicAirtableTestCleanupRoute: typeof ApiPublicAirtableTestCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-ethics': {
      id: '/code-of-ethics'
      path: '/code-of-ethics'
      fullPath: '/code-of-ethics'
      preLoaderRoute: typeof CodeOfEthicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeopathy': {
      id: '/homeopathy'
      path: '/homeopathy'
      fullPath: '/homeopathy'
      preLoaderRoute: typeof HomeopathyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoring': {
      id: '/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof MentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-patient-questionnaire': {
      id: '/new-patient-questionnaire'
      path: '/new-patient-questionnaire'
      fullPath: '/new-patient-questionnaire'
      preLoaderRoute: typeof NewPatientQuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/airtable-test-cleanup': {
      id: '/api/public/airtable-test-cleanup'
      path: '/api/public/airtable-test-cleanup'
      fullPath: '/api/public/airtable-test-cleanup'
      preLoaderRoute: typeof ApiPublicAirtableTestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CodeOfEthicsRoute: CodeOfEthicsRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContactRoute: ContactRoute,
  HomeopathyRoute: HomeopathyRoute,
  MentoringRoute: MentoringRoute,
  NewPatientQuestionnaireRoute: NewPatientQuestionnaireRoute,
  PrivacyRoute: PrivacyRoute,
  SupervisionRoute: SupervisionRoute,
  TermsRoute: TermsRoute,
  ApiPublicAirtableTestCleanupRoute: ApiPublicAirtableTestCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
